/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package notes.multi.console

import notes.multi.utilities.StringUtils

import org.apache.commons.text.WordUtils

fun main() {
    println("this is multi setup")
}
