/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package notes.multi.console

import notes.multi.utilities.Filemanager

import notes.multi.utilities.Note
import notes.multi.utilities.TextWindow
import javafx.application.Application

fun main() {
    // thesea re test functions feel free to use
    val n = Note()
    val noteTitle = n.title
    val noteContent = n.text.toString()
    println(noteContent)
    Application.launch(TextWindow()::class.java, "--title=${noteTitle}", "--text=${noteContent}")

    // val f = Filemanager("${System.getProperty("user.dir")}/test/", "hello.txt")
    // f.writefile("hello world")
    // f.deletefile()
    // println(f.openfile())
}
