/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package notes.multi.console
import java.lang.IllegalArgumentException

class ConsoleUtils {
    companion object {
        /**
         * Checks the `filename` inputted and throws an exception
         * if the `filename` does not follow the regular expression `pattern`
         * @param filename Name of the file
         * @param pattern Regular expression pattern
         * @throws IllegalArgumentException
         */
        fun verifyFilename(filename: String, pattern: Regex) {
            if (!(pattern matches filename)) {
                throw IllegalArgumentException("[ERROR]: File name does not follow the required input pattern")
            }
        }
    }
}
