/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package notes.multi.app
import java.lang.IllegalArgumentException

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      World!"

        /**
         * Checks the `filename` inputted and throws an exception
         * if the `filename` does not follow the regular expression `pattern`
         * @param filename Name of the file
         * @param pattern Regular expression pattern
         */
        fun verifyFilename(filename: String, pattern: Regex) {
            if (!(pattern matches filename)) {
                System.err.println("[ERROR]: File name does not follow the required input pattern")
                throw IllegalArgumentException("[ERROR]: File name does not follow the required input pattern")
            }
        }
    }
}
