/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package notes.multi.app


import javafx.application.Application
import notes.multi.utilities.DatabaseOperations
import notes.multi.utilities.Note
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.transactions.transaction
import java.time.LocalDate
import java.time.LocalDateTime
import javax.xml.crypto.Data
import notes.multi.utilities.TextWindow


fun main() {
    Database.connect("jdbc:sqlite:test.db")
    Application.launch(TextWindow()::class.java)
}
